name: todo_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  animated_theme_switcher: ^2.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1


  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/


  fonts:
     - family: Lugrasimo
       fonts:
         - asset: assets/fonts/lugrasimo-regular.ttf

           style: italic
     - family: Itim
       fonts:
         - asset: assets/fonts/Itim-Regular.ttf

